services:

  db:
    mem_limit: 256m
    cpu_shares: 256
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - local.env
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "dev-user",
          "-d",
          "currency_converter"
        ]
      interval: 5s
      retries: 5

  currency-converter-backend:
    image: currency-converter-backend:dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5000:80"
    command: /start-reload.sh
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - local.env

  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  db-data:
